baseurl: http://dendrite.tech/
languageCode: en-US
title: Dendrite
metadataFormat: yaml
pygmentsuseclasses: true
params:
  description: A columnar storage format for Clojure
  githubUrl: https://github.com/jwhitbeck/dendrite
  copyright: John Whitbeck 2015-2017
  themeColor: theme-base-0d
menu:
  main:
    - Name: "Github project page"
      URL: "https://github.com/jwhitbeck/dendrite"
      weight: 0
    - Name: "API docs"
      URL: "/api"
      weight: 2
